### ISSUE TITLE
It's not exactly playable

### ISSUE THREAD

**Issue by SenseiLeRoof** [Lakifume/True-Randomization#10]
Characters don't animate, and normal attack causes them to go unresponsive. Tested with old saves and new game.

**Comment by Lakifume** [comment]
That only happens if you mismatch the difficulty chosen in the mod with the difficulty chosen in-game. Since doing so can mess with the logic and make runs impossible I made it so that the player character isn't playable at all in case of a difficulty mismatch. Just pick the same difficulty in both.

**Comment by SenseiLeRoof** [comment]
Hmm, so it is. Good thing I kept my first-ever save (and it still works) so I could easily re-unlock Hard.
