### ISSUE TITLE
Question - Assign basic connectors new ids

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Lakifume/True-Randomization#13]
**Building maps is now much less restricted due to special doors being able to update based on room placement
Extra characters can now benefit from the overworld pool rando since it shuffles upgrades much more accurately**

**Comment by P3rf3ctXZer0** [comment]
Also can we copy rooms yet? (Instead of just making a map puzzle)

**Comment by Lakifume** [comment]
Beforehand I set the restrictions so that boss rooms stay connected to their vanilla adjacent rooms so that the boss doors would always lead into a boss, same for transition rooms and area doors. Now you can connect these special rooms to any other room and doors will be automatically placed accordingly, though not for the 4 backer rooms that are unlockable by keys since they have hardcoded transitions. Additionally bookshelves will always be placed next to save/warps rooms and empty entrances will be blocked by a closed door to prevent softlocks. So basically when building a map keep the restrictions option on so that you can always see the extent of your possibilities without causing any issues or oddities in-game. As for adding rooms into the game that will most likely not be possible for a long time.

**Comment by P3rf3ctXZer0** [comment]
Couldn't you just copy paste rooms and assign them unique ids? I mean obviouslly scripted rooms like boss rooms and event rooms couldn't be changed but I can't see why you could copy paste rooms like hallways connectors etc.

**Comment by Lakifume** [comment]
Turns out you are right, it is possible to add rooms into the game. I'll add support for it in the next update (saves, warps and transition rooms).

**Comment by P3rf3ctXZer0** [comment]
I will make you a thousand maps 🌠
