### ISSUE TITLE
Feature: Music Randomization

### ISSUE THREAD

**Issue by MainMemory** [Lakifume/True-Randomization#16]
I think it would be a neat option to have, if it's possible, whether it's just shuffling the existing music or allowing custom music.

**Comment by Lakifume** [comment]
I chose not to include any form of music randomization since it usually ends up being a recipe for disaster, you just get musics that don't fit the theme of the current area and sometimes musics that were meant to be heard for 30 seconds end up in places where you spend a large amount of time. I know other Castlevania randomizers do it but it's never given a good result. As for custom musics this mod only has one so far, the Dead Lands theme for the K2C area (instead of the vanilla underground waterways theme).

**Comment by MainMemory** [comment]
I feel like that's kind of the point, having music that doesn't fit the situation. As for music that's too short, you could specifically exclude those, or put them in a separate pool to be randomized amongst themselves.
