### ISSUE TITLE
Feature Request - True Castle Construction and Logic Management

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Lakifume/True-Randomization#4]
I noticed when making a castle you can only move parts which for one is very difficult to balance and for two why not create a drag and drop editor with clones of existing pieces but don't have those pieces contain any hard data like a boss spawns there but rather make it so the creator of the castle can scroll wheel in and see some low poly examples of what is there and allow them to place what kind of trigger can be there be it a boss room maybe a soul canister or treasure. I guess I am looking more like a mario maker or mega maker feel to castle building - I am impressed with this randomizer over the included one but I am used to playing PoR randomizer with castle shuffling. I can wait as long as it takes and if you have alpha testing you want to do contact me here. Zer0TheAvowedRD#2995

**Comment by Lakifume** [comment]
The modding limitations of Bloodstained would not allow me to go any farther than what my map editor already does. Moving rooms around is possible due to the fact that such data is stored in a single json file making the process very simple. What is inside of each room however is stored in many many files under the Environment folder of which format cannot be edited yet. That is also the reason why I am not quite able to shuffle Bloodless abilities around, that information is in those uneditable files as well.

**Comment by P3rf3ctXZer0** [comment]
That is a shame, I hope you can obfuscate the code someday :(
